// This file is generated by `npm run db:types` after running `npm run db:start`.
// Do not edit manually.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = Record<string, never>;
