// @spec docs/features/social/spec-db-foundation.md
import type { DbRow } from '@platform/supabase';
import { typedSupabase } from '@platform/supabase';
import { captureException } from '@platform/utils/captureException';

import { canTransition } from '../lib/partner-state-machine';
import type { GymPartner, PartnerInvite, PartnerStatus } from '../model/types';
import { PARTNER_STATUSES } from '../model/types';

type GymPartnerRow = DbRow<'gym_partners'>;

function toPartnerStatus(raw: string): PartnerStatus {
  if ((PARTNER_STATUSES as readonly string[]).includes(raw)) {
    return raw as PartnerStatus;
  }
  captureException(new Error(`Unknown partner status: ${raw}`));
  return 'removed';
}

function toGymPartner({
  row,
  currentUserId,
  partnerDisplayName,
}: {
  row: GymPartnerRow;
  currentUserId: string;
  partnerDisplayName: string | null;
}): GymPartner {
  const isRequester = row.requester_id === currentUserId;
  return {
    id: row.id,
    partnerId: isRequester ? row.responder_id : row.requester_id,
    partnerName: partnerDisplayName ?? 'Partner',
    status: toPartnerStatus(row.status),
    createdAt: row.created_at,
  };
}

export async function fetchAcceptedPartners() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('gym_partners')
    .select(
      '*, requester:profiles!gym_partners_requester_id_fkey(display_name), responder:profiles!gym_partners_responder_id_fkey(display_name)'
    )
    .or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`)
    .eq('status', 'accepted')
    .order('created_at', { ascending: false });

  if (error) {
    captureException(error);
    throw error;
  }

  return (data ?? []).map((row) => {
    const isRequester = row.requester_id === user.id;
    const partnerProfile = isRequester ? row.responder : row.requester;
    const displayName = partnerProfile?.display_name ?? null;
    return toGymPartner({
      row,
      currentUserId: user.id,
      partnerDisplayName: displayName,
    });
  });
}

export async function fetchPendingIncomingRequests() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('gym_partners')
    .select(
      '*, requester:profiles!gym_partners_requester_id_fkey(display_name)'
    )
    .eq('responder_id', user.id)
    .eq('status', 'pending')
    .order('created_at', { ascending: false });

  if (error) {
    captureException(error);
    throw error;
  }

  return (data ?? []).map((row) =>
    toGymPartner({
      row,
      currentUserId: user.id,
      partnerDisplayName: row.requester?.display_name ?? null,
    })
  );
}

export async function updatePartnerStatus({
  id,
  status,
}: {
  id: string;
  status: PartnerStatus;
}) {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Fetch current row to resolve role and validate transition
  const { data: row, error: fetchError } = await typedSupabase
    .from('gym_partners')
    .select('requester_id, status')
    .eq('id', id)
    .single();

  if (fetchError) {
    captureException(fetchError);
    throw fetchError;
  }

  const role = row.requester_id === user.id ? 'requester' : 'responder';
  const currentStatus = toPartnerStatus(row.status);

  if (!canTransition({ currentStatus, targetStatus: status, role })) {
    throw new Error(
      `Invalid transition: ${currentStatus} → ${status} as ${role}`
    );
  }

  const { error } = await typedSupabase
    .from('gym_partners')
    .update({ status })
    .eq('id', id);

  if (error) {
    captureException(error);
    throw error;
  }
}

export async function fetchAcceptedPartnerCount() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { count, error } = await typedSupabase
    .from('gym_partners')
    .select('id', { count: 'exact', head: true })
    .or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`)
    .eq('status', 'accepted');

  if (error) {
    captureException(error);
    throw error;
  }

  return count ?? 0;
}

export async function fetchCurrentUserDisplayName() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('profiles')
    .select('display_name')
    .eq('id', user.id)
    .single();

  if (error) {
    captureException(error);
    throw error;
  }

  return data?.display_name ?? null;
}

export async function createInvite() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Token generated by Postgres (gen_random_uuid default) — crypto.randomUUID()
  // is not available in React Native / Hermes.
  const { data, error } = await typedSupabase
    .from('gym_partner_invites')
    .insert({ inviter_id: user.id })
    .select('id, token')
    .single();

  if (error) {
    captureException(error);
    throw error;
  }

  return {
    id: data.id,
    token: data.token,
  } satisfies PartnerInvite;
}

export async function claimInvite({ token }: { token: string }) {
  // Atomic claim via SECURITY DEFINER RPC. Bypasses PostgREST/RLS quirks
  // with .update().select() chains that intermittently return empty.
  const { data, error } = await typedSupabase.rpc('claim_partner_invite', {
    p_token: token,
  });

  if (error) {
    switch (error.code) {
      case 'P0001':
        captureException(
          new Error(
            `claim_partner_invite: invalid (token prefix: ${token.slice(0, 8)})`
          )
        );
        throw new Error('Invite already claimed or invalid');
      case 'P0002':
        throw new Error('Cannot pair with yourself');
      case 'P0003':
        throw new Error('Already partnered with this user');
      default:
        captureException(error);
        throw error;
    }
  }

  const row = Array.isArray(data) ? data[0] : null;
  if (!row?.inviter_id) {
    const err = new Error(
      `claim_partner_invite returned empty (token prefix: ${token.slice(0, 8)})`
    );
    captureException(err);
    throw new Error('Invite already claimed or invalid');
  }

  // Inviter display_name not readable: profiles RLS only lets the requester read
  // the responder's profile after status='accepted'. UI falls back to 'partner'
  // until the inviter accepts. This protects against unsolicited pre-consent
  // display_name disclosure to anyone holding a target's UUID.
  return {
    inviterId: row.inviter_id as string,
    inviterName: null,
  };
}
