import type { DbRow } from '@platform/supabase';
import { typedSupabase } from '@platform/supabase';
import { captureException } from '@platform/utils/captureException';

import { canTransition } from '../lib/partner-state-machine';
import type { GymPartner, PartnerInvite, PartnerStatus } from '../model/types';
import { PARTNER_STATUSES } from '../model/types';

type GymPartnerRow = DbRow<'gym_partners'>;

function toPartnerStatus(raw: string): PartnerStatus {
  if ((PARTNER_STATUSES as readonly string[]).includes(raw)) {
    return raw as PartnerStatus;
  }
  captureException(new Error(`Unknown partner status: ${raw}`));
  return 'removed';
}

function toGymPartner({
  row,
  currentUserId,
  partnerDisplayName,
}: {
  row: GymPartnerRow;
  currentUserId: string;
  partnerDisplayName: string | null;
}): GymPartner {
  const isRequester = row.requester_id === currentUserId;
  return {
    id: row.id,
    partnerId: isRequester ? row.responder_id : row.requester_id,
    partnerName: partnerDisplayName ?? 'Partner',
    status: toPartnerStatus(row.status),
    createdAt: row.created_at,
  };
}

export async function fetchAcceptedPartners() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('gym_partners')
    .select(
      '*, requester:profiles!gym_partners_requester_id_fkey(display_name), responder:profiles!gym_partners_responder_id_fkey(display_name)'
    )
    .or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`)
    .eq('status', 'accepted')
    .order('created_at', { ascending: false });

  if (error) {
    captureException(error);
    throw error;
  }

  return (data ?? []).map((row) => {
    const isRequester = row.requester_id === user.id;
    const partnerProfile = isRequester ? row.responder : row.requester;
    const displayName = partnerProfile?.display_name ?? null;
    return toGymPartner({
      row,
      currentUserId: user.id,
      partnerDisplayName: displayName,
    });
  });
}

export async function fetchPendingIncomingRequests() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('gym_partners')
    .select(
      '*, requester:profiles!gym_partners_requester_id_fkey(display_name)'
    )
    .eq('responder_id', user.id)
    .eq('status', 'pending')
    .order('created_at', { ascending: false });

  if (error) {
    captureException(error);
    throw error;
  }

  return (data ?? []).map((row) =>
    toGymPartner({
      row,
      currentUserId: user.id,
      partnerDisplayName: row.requester?.display_name ?? null,
    })
  );
}

export async function updatePartnerStatus({
  id,
  status,
}: {
  id: string;
  status: PartnerStatus;
}) {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Fetch current row to resolve role and validate transition
  const { data: row, error: fetchError } = await typedSupabase
    .from('gym_partners')
    .select('requester_id, status')
    .eq('id', id)
    .single();

  if (fetchError) {
    captureException(fetchError);
    throw fetchError;
  }

  const role = row.requester_id === user.id ? 'requester' : 'responder';
  const currentStatus = toPartnerStatus(row.status);

  if (!canTransition({ currentStatus, targetStatus: status, role })) {
    throw new Error(
      `Invalid transition: ${currentStatus} → ${status} as ${role}`
    );
  }

  const { error } = await typedSupabase
    .from('gym_partners')
    .update({ status })
    .eq('id', id);

  if (error) {
    captureException(error);
    throw error;
  }
}

export async function fetchAcceptedPartnerCount() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { count, error } = await typedSupabase
    .from('gym_partners')
    .select('id', { count: 'exact', head: true })
    .or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`)
    .eq('status', 'accepted');

  if (error) {
    captureException(error);
    throw error;
  }

  return count ?? 0;
}

export async function fetchCurrentUserDisplayName() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('profiles')
    .select('display_name')
    .eq('id', user.id)
    .single();

  if (error) {
    captureException(error);
    throw error;
  }

  return data?.display_name ?? null;
}

export async function createInvite() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Token generated by Postgres (gen_random_uuid default) — crypto.randomUUID()
  // is not available in React Native / Hermes.
  const { data, error } = await typedSupabase
    .from('gym_partner_invites')
    .insert({ inviter_id: user.id })
    .select('id, token')
    .single();

  if (error) {
    captureException(error);
    throw error;
  }

  return {
    id: data.id,
    token: data.token,
  } satisfies PartnerInvite;
}

export async function claimInvite({ token }: { token: string }) {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Atomic claim: RLS USING clause enforces claimed_by IS NULL using server-side
  // evaluation — no client-side check needed or safe. Invites never expire.
  // No embed: profiles RLS hides other users' profiles, which would null the row.
  const { data, error } = await typedSupabase
    .from('gym_partner_invites')
    .update({ claimed_by: user.id })
    .eq('token', token)
    .select('inviter_id')
    .maybeSingle();

  if (error) {
    captureException(error);
    throw error;
  }

  if (!data) {
    const err = new Error(
      `Invite already claimed or invalid (token prefix: ${token.slice(0, 8)})`
    );
    captureException(err);
    throw new Error('Invite already claimed or invalid');
  }

  // Self-claim guard — unclaim first so the invite token stays usable
  if (data.inviter_id === user.id) {
    await typedSupabase
      .from('gym_partner_invites')
      .update({ claimed_by: null })
      .eq('token', token)
      .eq('claimed_by', user.id);
    throw new Error('Cannot pair with yourself');
  }

  // Create the partnership. If this fails (e.g. duplicate pair), unclaim the invite
  // so the token can be retried — prevents dead-end "claimed but no partnership" state.
  const { error: partnerError } = await typedSupabase
    .from('gym_partners')
    .insert({
      requester_id: user.id,        // scanner sends the request
      responder_id: data.inviter_id, // inviter accepts/declines
    });

  if (partnerError) {
    // Roll back the claim so the invite token remains usable
    const { error: rollbackError } = await typedSupabase
      .from('gym_partner_invites')
      .update({ claimed_by: null })
      .eq('token', token)
      .eq('claimed_by', user.id);

    if (rollbackError) {
      captureException(rollbackError);
    }

    captureException(partnerError);
    throw partnerError;
  }

  // Inviter display_name not readable: profiles RLS hides other users.
  // UI falls back to 'partner'.
  return {
    inviterId: data.inviter_id,
    inviterName: null,
  };
}
