import type { DbRow, Json } from '@platform/supabase';
import { typedSupabase } from '@platform/supabase';
import { captureException } from '@platform/utils/captureException';

import { canTransition } from '../lib/partner-state-machine';
import type { GymPartner, PartnerInvite, PartnerStatus } from '../model/types';

type GymPartnerRow = DbRow<'gym_partners'>;

function toGymPartner({
  row,
  currentUserId,
  partnerDisplayName,
}: {
  row: GymPartnerRow;
  currentUserId: string;
  partnerDisplayName: string | null;
}): GymPartner {
  const isRequester = row.requester_id === currentUserId;
  return {
    id: row.id,
    partnerId: isRequester ? row.responder_id : row.requester_id,
    partnerName: partnerDisplayName ?? 'Partner',
    status: row.status as PartnerStatus,
    createdAt: row.created_at,
  };
}

export async function fetchAcceptedPartners() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('gym_partners')
    .select(
      '*, requester:profiles!gym_partners_requester_id_fkey(display_name), responder:profiles!gym_partners_responder_id_fkey(display_name)',
    )
    .or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`)
    .eq('status', 'accepted')
    .order('created_at', { ascending: false });

  if (error) {
    captureException(error);
    throw error;
  }

  return (data ?? []).map((row) => {
    const isRequester = row.requester_id === user.id;
    const partnerProfile = isRequester ? row.responder : row.requester;
    const displayName = partnerProfile?.display_name ?? null;
    return toGymPartner({ row, currentUserId: user.id, partnerDisplayName: displayName });
  });
}

export async function fetchPendingIncomingRequests() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('gym_partners')
    .select(
      '*, requester:profiles!gym_partners_requester_id_fkey(display_name)',
    )
    .eq('responder_id', user.id)
    .eq('status', 'pending')
    .order('created_at', { ascending: false });

  if (error) {
    captureException(error);
    throw error;
  }

  return (data ?? []).map((row) =>
    toGymPartner({
      row,
      currentUserId: user.id,
      partnerDisplayName: row.requester?.display_name ?? null,
    }),
  );
}

export async function updatePartnerStatus({
  id,
  status,
}: {
  id: string;
  status: PartnerStatus;
}) {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Fetch current row to resolve role and validate transition
  const { data: row, error: fetchError } = await typedSupabase
    .from('gym_partners')
    .select('requester_id, status')
    .eq('id', id)
    .single();

  if (fetchError) {
    captureException(fetchError);
    throw fetchError;
  }

  const role = row.requester_id === user.id ? 'requester' : 'responder';
  const currentStatus = row.status as PartnerStatus;

  if (!canTransition({ currentStatus, targetStatus: status, role })) {
    throw new Error(
      `Invalid transition: ${currentStatus} → ${status} as ${role}`,
    );
  }

  const { error } = await typedSupabase
    .from('gym_partners')
    .update({ status })
    .eq('id', id);

  if (error) {
    captureException(error);
    throw error;
  }
}

export async function fetchAcceptedPartnerCount() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { count, error } = await typedSupabase
    .from('gym_partners')
    .select('id', { count: 'exact', head: true })
    .or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`)
    .eq('status', 'accepted');

  if (error) {
    captureException(error);
    throw error;
  }

  return count ?? 0;
}

export async function fetchCurrentUserDisplayName() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('profiles')
    .select('display_name')
    .eq('id', user.id)
    .single();

  if (error) {
    captureException(error);
    throw error;
  }

  return data?.display_name ?? null;
}

export async function createInvite() {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString();

  // Token generated by Postgres (gen_random_uuid default) — crypto.randomUUID()
  // is not available in React Native / Hermes.
  const { data, error } = await typedSupabase
    .from('gym_partner_invites')
    .insert({
      inviter_id: user.id,
      expires_at: expiresAt,
    })
    .select('id, token, expires_at')
    .single();

  if (error) {
    captureException(error);
    throw error;
  }

  return {
    id: data.id,
    token: data.token,
    expiresAt: data.expires_at,
  } satisfies PartnerInvite;
}

export async function claimInvite({ token }: { token: string }) {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Atomic claim: only succeeds if unclaimed and unexpired
  const { data, error } = await typedSupabase
    .from('gym_partner_invites')
    .update({ claimed_by: user.id })
    .eq('token', token)
    .is('claimed_by', null)
    .gt('expires_at', new Date().toISOString())
    .select('inviter_id, inviter:profiles!gym_partner_invites_inviter_id_fkey(display_name)')
    .maybeSingle();

  if (error) {
    captureException(error);
    throw error;
  }

  if (!data) {
    throw new Error('Invite expired or already claimed');
  }

  // Self-claim guard — unclaim first so the invite token stays usable
  if (data.inviter_id === user.id) {
    await typedSupabase
      .from('gym_partner_invites')
      .update({ claimed_by: null })
      .eq('token', token)
      .eq('claimed_by', user.id);
    throw new Error('Cannot pair with yourself');
  }

  // Create the partnership. If this fails (e.g. duplicate pair), unclaim the invite
  // so the token can be retried — prevents dead-end "claimed but no partnership" state.
  const { error: partnerError } = await typedSupabase
    .from('gym_partners')
    .insert({
      requester_id: data.inviter_id,
      responder_id: user.id,
    });

  if (partnerError) {
    // Roll back the claim so the invite token remains usable
    const { error: rollbackError } = await typedSupabase
      .from('gym_partner_invites')
      .update({ claimed_by: null })
      .eq('token', token)
      .eq('claimed_by', user.id);

    if (rollbackError) {
      captureException(rollbackError);
    }

    captureException(partnerError);
    throw partnerError;
  }

  return {
    inviterId: data.inviter_id,
    inviterName: data.inviter?.display_name ?? null,
  };
}

// ── Partner video insert ─────────────────────────────────────────────────────

export async function insertPartnerSessionVideo({
  targetUserId,
  sessionId,
  lift,
  setNumber,
  cameraAngle = 'side',
  localUri,
  durationSec,
  analysis,
}: {
  targetUserId: string;
  sessionId: string;
  lift: string;
  setNumber: number;
  cameraAngle?: 'side' | 'front';
  localUri: string;
  durationSec: number;
  analysis?: Json;
}) {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await typedSupabase
    .from('session_videos')
    .insert({
      user_id: targetUserId,
      recorded_by: user.id,
      session_id: sessionId,
      lift,
      set_number: setNumber,
      camera_angle: cameraAngle,
      local_uri: localUri,
      duration_sec: durationSec,
      ...(analysis != null ? { analysis } : {}),
    })
    .select('id')
    .single();

  if (error) {
    captureException(error);
    throw error;
  }

  return { videoId: data.id };
}

// ── Partner session visibility ───────────────────────────────────────────────

export interface PartnerActiveSession {
  id: string;
  status: string;
  primaryLift: string | null;
  plannedSets: unknown;
}

export async function fetchPartnerActiveSession({
  partnerId,
}: {
  partnerId: string;
}) {
  const { data, error } = await typedSupabase
    .from('sessions')
    .select('id, status, primary_lift, planned_sets')
    .eq('user_id', partnerId)
    .eq('status', 'in_progress')
    .order('created_at', { ascending: false })
    .maybeSingle();

  if (error) {
    captureException(error);
    throw error;
  }

  if (!data) return null;

  return {
    id: data.id,
    status: data.status,
    primaryLift: data.primary_lift,
    plannedSets: data.planned_sets,
  } satisfies PartnerActiveSession;
}

export function subscribeToPartnerSessions({
  partnerIds,
  onUpdate,
}: {
  partnerIds: string[];
  onUpdate: (partnerId: string) => void;
}) {
  if (partnerIds.length === 0) return () => {};

  const channel = typedSupabase
    .channel('partner-sessions')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'sessions',
        filter: `user_id=in.(${partnerIds.join(',')})`,
      },
      (payload) => {
        const userId =
          (payload.new as Record<string, unknown>)?.user_id as
            | string
            | undefined;
        if (userId) onUpdate(userId);
      },
    )
    .subscribe();

  return () => {
    typedSupabase.removeChannel(channel);
  };
}

// ── Partner video badge ──────────────────────────────────────────────────────

export async function fetchUnseenPartnerVideoCount({
  sinceTimestamp,
}: {
  sinceTimestamp: string | null;
}) {
  const {
    data: { user },
  } = await typedSupabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  let query = typedSupabase
    .from('session_videos')
    .select('id', { count: 'exact', head: true })
    .eq('user_id', user.id)
    .not('recorded_by', 'is', null);

  if (sinceTimestamp) {
    query = query.gt('created_at', sinceTimestamp);
  }

  const { count, error } = await query;

  if (error) {
    captureException(error);
    throw error;
  }

  return count ?? 0;
}

export function subscribeToPartnerVideoInserts({
  onInsert,
}: {
  onInsert: () => void;
}) {
  const channel = typedSupabase
    .channel('partner-video-inserts')
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'session_videos',
      },
      (payload) => {
        const recordedBy = (payload.new as Record<string, unknown>)
          ?.recorded_by;
        if (recordedBy != null) {
          onInsert();
        }
      },
    )
    .subscribe();

  return () => {
    typedSupabase.removeChannel(channel);
  };
}
